const express=require("express")
const router=express.Router()
const {signUp,loginUser,adminLogin,userProfile,updateUser,deleteUser}=require("../controllers/authController.js")
const auth=require("../middlewares/auth.js")
router.post("/signup",signUp)
router.post("/userlogin",loginUser)
router.post("/adminlogin",adminLogin)
router.get("/profile",auth,userProfile)
router.put("/updateuser",auth,updateUser)
router.delete("/deleteuser",auth,deleteUser)
module.exports=router
